<a href="https://colab.research.google.com/github/yangyeji2020311166/ML/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


from sklearn.datasets import load_breast_cancer
breastcancer_dataset=load_breast_cancer()
print("breastcancer_dataset의 키:\n", breastcancer_dataset.keys())

breastcancer_dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
print(breastcancer_dataset['data'])
print(type(breastcancer_dataset['data']))
print(breastcancer_dataset['target'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
<class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 

In [16]:
import math
import random
zValue = [0,0,0,0,0,0,0]
FinalzValue = [0,0,0,0,0,0,0]

a = random.uniform(-1,1)
b = random.uniform(-1,1)
c = random.uniform(-1,1)
d = random.uniform(-1,1)
e = random.uniform(-1,1)
f = random.uniform(-1,1)
g = random.uniform(-1,1)
h = random.uniform(-1,1)
i = random.uniform(-1,1)

eta = 0.0001

def sigmoid(x):
    return 1.0/(1.0+math.exp(-x))

data = breastcancer_dataset['data']
labels = breastcancer_dataset['target']

for counter in range(1000):
    da=db=dc=dd=de=df=dg=dh=di=0.0
    for index in range(len(data)):
        x = float(data[index][0])
        y = float(data[index][1])
        z1 = a*x+b*y+c
        X = sigmoid(z1)
        z2 = d*x+e*y+f
        Y = sigmoid(z2)
        z = g*X+h*Y+i
        Z = labels[index]
        dz = 2*(z-Z)
        dz1 = dz*g*sigmoid(z1)*(1.0-sigmoid(z1))
        dz2 = dz*h*sigmoid(z2)*(1.0-sigmoid(z2))
        da += dz1*x
        db += dz1*y
        dc += dz1
        dd += dz2*x
        de += dz2*y
        df += dz2
        dg += dz*X
        dh += dz*Y
        di += dz

    a = a-eta*da
    b = b-eta*db
    c = c-eta*dc
    d = d-eta*dd
    e = e-eta*de
    f = f-eta*df
    g = g-eta*dg
    h = h-eta*dh
    i = i-eta*di
    
print("a=%lf, b = %lf, c = %lf, d = %lf, e = %lf, f = %lf, g = %lf, h = %lf, i = %lf" % (a,b,c,d,e,f,g,h,i))


a=-0.263068, b = 0.536833, c = 0.912720, d = 0.777354, e = -0.002941, f = 0.684717, g = -0.108795, h = 0.806535, i = -0.070617
